---
version: 2.1
common-steps:
  - &installdeps
    run:
      name: Install RPM packaging dependencies
      command: |
        yum -y update && yum -y install git-lfs
jobs:
  check-sigs:
    docker:
      - image: fedora:37
    steps:
      - checkout
      - *installdeps
      - run:
          name: Verify signatures on all RPMs
          command: |
            git lfs install && git lfs pull
            rpm --import fpf-yum-tools-archive-keyring.gpg
            for i in dangerzone/*/*.rpm; do rpm --checksig "$i"; done
workflows:
  check-packages:
    jobs:
      - check-sigs
